// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoginUser(arg1, arg2) {
  return window['go']['handlers']['UsersHandler']['LoginUser'](arg1, arg2);
}

export function RegisterUser(arg1, arg2, arg3) {
  return window['go']['handlers']['UsersHandler']['RegisterUser'](arg1, arg2, arg3);
}
