// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function RegisterUser(arg1:string,arg2:string,arg3:string):Promise<models.RegisterUserResponse>;
